### ISSUE TITLE
Fix path to itemizedlist.gif

### ISSUE THREAD

**Issue by tbazant** [openSUSE/suse-vscode-doc#15]
It's not showing correctly neither at https://marketplace.visualstudio.com/items?itemName=opensuse.docbook-snippets&ssr=false#overview, not at https://open-vsx.org/extension/openSUSE/docbook-snippets

**Comment by tbazant** [comment]
Maybe use a full path https://github.com/openSUSE/suse-vscode-doc/blob/main/extensions/docbook-snippets/media/itemizedlist.gif ?

**Comment by tbazant** [comment]
Currently, they point to https://github.com/openSUSE/suse-vscode-doc/blob/HEAD/media/itemizedlist.gif which does not exist.

**Comment by tomschr** [comment]
Strange. I works in VSCode, but not in the marketplace. :thinking:

I'll use the URL that you've suggested in https://github.com/openSUSE/suse-vscode-doc/issues/15#issuecomment-1446336380
