### ISSUE TITLE
Is Might an accepted word or not

### ISSUE THREAD

**Issue by Amrita42** [openSUSE/suse-vscode-doc#26]
Vale suggests removing **might**  but https://documentation.suse.com/style/current/single-html/docu_styleguide/#art-styleguide  states that might is an accepted word.

**Comment by tbazant** [comment]
@dariavladykina i guess 'may' is better than 'might', right?

**Comment by dariavladykina** [comment]
I think we should leave the guidance in DSG as it is (use might to express a possibility, only use may to express permissions sought/given) and ask Vale to not penalize texts for any of them.
